"""turbulence.py -- opt-in atmospheric-turbulence layer: dense 2D Kolmogorov/von-Karman phase screens.

The engine's AO module (`ao_kolmogorov`) injects a MODAL 15-Zernike caricature; this module adds the DENSE
sampled phase screen the modal channel cannot represent -- a 2D random phase field with the correct
Kolmogorov spatial statistics, generated by the Fourier-transform method (filter complex Gaussian white
noise by sqrt(PSD), IFFT) with sub-harmonic low-frequency compensation (Lane/Johansson-Gavel, after Schmidt
2010 ch.9). It is on-demand analysis like wave.py / field.py: it does NOT touch the live ray tracer, so the
trace stays byte-identical. RNG is a SEED-PINNED local Generator (np.random.default_rng) -- no global state.
A screen can be fed to field.angular_spectrum for a single-screen (seeing/speckle) PSF.

Physics (constants physics_verify ok=true this session):
  Kolmogorov phase PSD   Phi_phi(kappa) = 0.023 r0^(-5/3) kappa^(-11/3)              (Schmidt 9.x)
  von Karman             Phi_phi = 0.023 r0^(-5/3) exp(-(k/km)^2) / (k^2 + k0^2)^(11/6),  km=5.92/l0, k0=2pi/L0
  structure function     D_phi(r) = 6.88 (r/r0)^(5/3)   [rad^2];  6.88 = 2*(24/5*Gamma(6/5))^(5/6) = 6.8839
r0 (Fried parameter) is DEFINED so that D_phi(r0) = 6.88 rad^2. The generated screen's measured structure
function reproduces 6.88 (r/r0)^(5/3) once sub-harmonics restore the low-frequency tail -- validated in
tests/test_validation.py (this is exactly the check Schmidt performs).
"""
from __future__ import annotations

import math

import numpy as np

MM = 1.0  # this module works in whatever length unit r0/dx share (mm by the bench convention)
STRUCT_CONST = 6.8839  # 2*(24/5*Gamma(6/5))^(5/6), Kolmogorov structure-function constant


def _psd_phi(f, r0, L0_mm, l0_mm):
    """Kolmogorov (L0=inf, l0=0) or von-Karman phase PSD on a spatial-frequency grid f [cyc/length]."""
    f0 = 0.0 if (L0_mm is None or not np.isfinite(L0_mm)) else 1.0 / L0_mm
    out = 0.023 * r0 ** (-5.0 / 3.0) / (f * f + f0 * f0) ** (11.0 / 6.0)
    if l0_mm:
        fm = 5.92 / l0_mm / (2.0 * math.pi)
        out = out * np.exp(-(f / fm) ** 2)
    return out


def kolmogorov_screen(n_grid, dx_mm, r0_mm, L0_mm=None, l0_mm=None, seed=0, subharmonics=3):
    """A dense 2D phase screen [radians] with Kolmogorov (or von-Karman) statistics, FT method + sub-harmonics.

    n_grid x n_grid samples at pitch dx_mm; Fried parameter r0_mm. L0_mm/l0_mm give the von-Karman outer/inner
    scales (default = pure Kolmogorov). Seed-pinned local RNG. Returns the real phase screen (zero-mean)."""
    n = int(n_grid)
    rng = np.random.default_rng(int(seed))
    del_f = 1.0 / (n * dx_mm)                                   # frequency-grid spacing [cyc/length]
    fx = (np.arange(-n // 2, n // 2)) * del_f
    FX, FY = np.meshgrid(fx, fx)
    f = np.sqrt(FX * FX + FY * FY)
    f[n // 2, n // 2] = 1.0                                     # avoid /0 at DC; PSD there is zeroed next
    psd = _psd_phi(f, r0_mm, L0_mm, l0_mm)
    psd[n // 2, n // 2] = 0.0
    cn = (rng.standard_normal((n, n)) + 1j * rng.standard_normal((n, n))) * np.sqrt(psd) * del_f
    # ift2(cn, 1) = ifftshift(ifft2(ifftshift(.)))*N^2 (Schmidt): the del_f is already folded into cn, so the
    # IFFT just undoes numpy's 1/N^2 -> the real-space phase screen whose variance is integral(PSD) d^2kappa.
    phz = np.real(np.fft.ifftshift(np.fft.ifft2(np.fft.ifftshift(cn))) * n ** 2)
    # sub-harmonic low-frequency compensation: add coarse modes the FFT grid under-samples
    phz = phz + _subharmonics(n, dx_mm, r0_mm, L0_mm, l0_mm, rng, subharmonics)
    return phz - phz.mean()


def _subharmonics(n, dx_mm, r0_mm, L0_mm, l0_mm, rng, levels):
    """Lane/Johansson-Gavel sub-harmonic compensation: `levels` octaves of 3x3 low-freq modes (Schmidt 2010)."""
    if not levels:
        return 0.0
    x = (np.arange(-n // 2, n // 2)) * dx_mm
    X, Y = np.meshgrid(x, x)
    sh = np.zeros((n, n))
    for p in range(1, int(levels) + 1):
        del_f = 1.0 / (3.0 ** p * n * dx_mm)                   # finer frequency spacing each octave
        fx = np.array([-1.0, 0.0, 1.0]) * del_f
        FX, FY = np.meshgrid(fx, fx)
        f = np.sqrt(FX * FX + FY * FY)
        f[1, 1] = 1.0
        psd = _psd_phi(f, r0_mm, L0_mm, l0_mm)
        psd[1, 1] = 0.0
        cn = (rng.standard_normal((3, 3)) + 1j * rng.standard_normal((3, 3))) * np.sqrt(psd) * del_f
        for i in range(3):
            for j in range(3):
                sh = sh + np.real(cn[i, j] * np.exp(1j * 2.0 * math.pi * (FX[i, j] * X + FY[i, j] * Y)))
    return sh - sh.mean()


def structure_function(screen, dx_mm, seps_px=None):
    """Measured phase structure function D(r)=<[phi(x+r)-phi(x)]^2> [rad^2] at separations seps_px (x-shifts).

    Returns {r_mm: [...], D: [...]} -- averaged over both axes for isotropy."""
    if seps_px is None:
        seps_px = [1, 2, 4, 8, 16, 32]
    r_mm, D = [], []
    for s in seps_px:
        s = int(s)
        if s <= 0 or s >= screen.shape[0]:
            continue
        dx_diff = screen[:, s:] - screen[:, :-s]
        dy_diff = screen[s:, :] - screen[:-s, :]
        d = 0.5 * (float(np.mean(dx_diff ** 2)) + float(np.mean(dy_diff ** 2)))
        r_mm.append(s * dx_mm)
        D.append(d)
    return {"r_mm": r_mm, "D": D}


def screen_metrics(screen, dx_mm, r0_mm, png_path=None):
    """Validate a screen against Kolmogorov theory: measured RMS, the structure function, and the fitted r0.

    The measured D(r) should track 6.88 (r/r0)^(5/3); `r0_fit_mm` back-solves r0 from D at a mid separation.
    Returns {ok, rms_rad, r_mm, D_meas, D_theory, ratio_mid, r0_fit_mm, n_grid, dx_mm}."""
    n = screen.shape[0]
    rms = float(np.sqrt(np.mean((screen - screen.mean()) ** 2)))
    seps = [max(1, n // 32), max(1, n // 16), max(1, n // 8), max(1, n // 4)]
    sf = structure_function(screen, dx_mm, seps)
    r = np.asarray(sf["r_mm"])
    Dm = np.asarray(sf["D"])
    Dt = STRUCT_CONST * (r / r0_mm) ** (5.0 / 3.0)
    mid = len(r) // 2
    # back-solve r0 from the measured D at the mid separation: D = 6.88 (r/r0)^(5/3) -> r0 = r / (D/6.88)^(3/5)
    r0_fit = float(r[mid] / (Dm[mid] / STRUCT_CONST) ** (3.0 / 5.0)) if Dm[mid] > 0 else None
    out = {
        "ok": True,
        "rms_rad": round(rms, 4),
        "r_mm": [round(v, 3) for v in r.tolist()],
        "D_meas": [round(v, 4) for v in Dm.tolist()],
        "D_theory": [round(v, 4) for v in Dt.tolist()],
        "ratio_mid": round(float(Dm[mid] / Dt[mid]), 4) if Dt[mid] > 0 else None,
        "r0_fit_mm": round(r0_fit, 3) if r0_fit else None,
        "n_grid": n, "dx_mm": round(dx_mm, 5),
    }
    if png_path:
        try:
            _render_screen(screen, out, png_path)
            out["png"] = png_path
        except Exception as exc:
            out["png_error"] = str(exc)
    return out


def _render_screen(screen, meta, png_path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    span = meta["dx_mm"] * screen.shape[0] / 2.0
    fig, ax = plt.subplots(figsize=(5, 5))
    im = ax.imshow(screen, cmap="twilight", extent=[-span, span, -span, span], interpolation="nearest")
    ax.set_title("Kolmogorov phase screen  RMS=%.2f rad  r0_fit=%.1f mm" % (meta["rms_rad"], meta["r0_fit_mm"]))
    ax.set_xlabel("mm")
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="phase [rad]")
    fig.savefig(png_path, dpi=110, bbox_inches="tight", facecolor="#0d0d10")
    plt.close(fig)
